### ISSUE TITLE
[enhanced] Sugestao de melhoria

### ISSUE THREAD

**Issue by lue93** [leticialevleitao/estudosApiALURA#2]
Ola, tudo bem ?

Gostaria de fazer uma contribuicao, sugerindo uma melhoria nesse projeto, mesmo que seja de estudo. 

Poderia mover esse trecho de codigo para uma funcao geradora contida em uma classe RG, semelhante ao pacote que usou para gerar o CPF. (inclusive me surgiu a duvida por que nao existe suporte ao RG la)
https://github.com/leticialevleitao/estudosApiALURA/blob/60ea4da28158a3c8124b801a78aab2580c1ec2dd/populate_script.py#L20

:)

**Comment by leticialevleitao** [comment]
Oii, tudo sim! 
Muito obrigada pela sugestão, de fato me parece interessante e mais 'limpo' tb.
